### ISSUE TITLE
[Feature request]在readme或者代码中提供更好的接口访问指引

### ISSUE THREAD

**Issue by yilihjy** [liou666/polyglot#11]
目前readme里面[常见问题](https://github.com/liou666/polyglot/blob/main/README.md?plain=1#L61)关于这块的描述太简洁，如果考虑能让更多人使用。
可以考虑考虑类似的接入方案：
[api2d-js](https://github.com/easychen/api2d-js)
[api2d](https://api2d.com/r/186772)
这样更容易让普通用户自助使用

**Comment by liou666** [comment]
@yilihjy 感谢你的建议，后续会考虑加上[api2d](https://api2d.com/r/186772)的接口。
