### ISSUE TITLE
[功能需求] 开源模型接口以及提供linux支持

### ISSUE THREAD

**Issue by im-ki** [liou666/polyglot#13]
#### Describe the problem you confuse
[功能需求] 很不错的软件。我想问一下之后会不会考虑提供Vicuna、ChatGLM等开源模型的接口？还有就是会不会提供linux版的？谢谢

**Comment by liou666** [comment]
@im-ki 感谢使用该软件。
有计划加入其他的开源模型接口（目前想的是加入new Bing接口），也欢迎大家提pr把自己想要的模型接口加进去。
项目是跨平台的，之后会打包Liunx版本，发布出来。

**Comment by liou666** [comment]
linux版本目前以支持
