### ISSUE TITLE
[Bug] replay audio

### ISSUE THREAD

**Issue by scaactk** [liou666/polyglot#14]
#### Describe the bug
点击语音播放按钮的时候，声音没播完的情况下，再点一次，播放会加入队列，点击几次会连续播放几次。按常见的UI交互方式，应该点第二次停止播放。每次播放队列中仅存一条语音。besides, 不知道有没有本地缓存机制

**Comment by liou666** [comment]
@scaactk 感谢反馈，不过我认为按照微信的语音做法，点击第二次从头播放会更合适一些🤔；btw, 目前没加本次缓存，后续会考虑加上提高性能。

**Comment by scaactk** [comment]
感谢，博主加油
