### ISSUE TITLE
[Feature] 兼容api2d接口

### ISSUE THREAD

**Issue by liuruidong4** [liou666/polyglot#17]
#### Describe the problem you confuse
大佬我想给女朋友用，我现在的openai api用的是api2d的，代理选它的填api填它的，在你这好像不能用，它api格式好像不一样，其他软件就是正常填上去代理改好就好了。
这里提示输入正确的apikey是不是限制了格式呀，那个跟官方的不太一样，大佬能不能去掉限制打包一个版本。（个人觉得是这个原因又不会弄）
谢谢啦˃ʍ˂

**Comment by liou666** [comment]
#11 与这个issue是重复的。
@liuruidong4 目前还没有兼容api2d的api，只能输入openai 的apikey，之后会替换为api2d的接口。
