### ISSUE TITLE
[Help] 对话过程中可语速调整

### ISSUE THREAD

**Issue by Eventidus** [liou666/polyglot#20]
#### Describe the problem you confuse
能否增加在对话过程中也可以进行语速调整功能呢?

**Comment by liou666** [comment]
@Iambihua 之后会增加新建角色时，音色语速可预览功能。在新建时候就选择一个合适的音色和语速，对话过程中就不需要再次调整了。如需要不同的音色或语速，新建一个对话即可。#12
