### ISSUE TITLE
【建议】预置场景

### ISSUE THREAD

**Issue by 0000005** [liou666/polyglot#21]
建议预置一些场景，每次对话要在一个场景中解决具体的问题。这样对话练习才更有目的性，和针对性。
不然漫无目的的瞎聊，其实得不到什么提升。

场景比如：
- 你要向一位新员工介绍公司，直到员工满意为止。
- 你要买一件衣服，你的任务是把价格从 100 美元 还到 50 美元。
等等等等。

每次对话，都要解决具体的问题。让ai 故意刁难练习者。

**Comment by liou666** [comment]
感谢建议，之后会在新建角色的时候支持选择一些内置对话场景
