### ISSUE TITLE
[Help]送的18元套餐的API key不能用吗？

### ISSUE THREAD

**Issue by UIWP0** [liou666/polyglot#22]
#### Describe the problem you confuse
![image](https://user-images.githubusercontent.com/32759429/233784781-9cf35cef-0933-4cd2-9159-ede0cd51fc96.png)

**Comment by liou666** [comment]
可以用；这个提示是你的apikey免费额度用完了或者过期了，请检查一下你的api额度

**Comment by liuruidong4** [comment]
18的应该都是4.1就过期了呀。
