### ISSUE TITLE
[建议] api地址

### ISSUE THREAD

**Issue by xiaoer666** [liou666/polyglot#26]
#### 添加baseURL设置
很nice的作品，有个小建议，现在由于OpenAI的封禁，很难去直接付费OpenAI的官方接口。所以：

能否添加API请求的baseURL设置（包括我在内的很多人都是通过第三方套壳API来调用OpenAI服务的）

**Comment by liou666** [comment]
@xiaoer666 感谢建议。 对于提到的支持设置baseURL，我理解这个可以通过在现应用中设置代理完成。另外，目前项目已经兼容了api2d的key，方便更多用户选择 #11。
