### ISSUE TITLE
[有个小问题] 目前使用来看, 软件接收语音的时间太短了, 我话还没说完, ai就开始和我对话了

### ISSUE THREAD

**Issue by gaoxuxu110** [liou666/polyglot#27]
希望可以添加`手动开启`录音, `手动结束`录音的功能, 这样有助于新手对话(我这种新手说话比较慢,hh)

**Comment by liou666** [comment]
@gaoxuxu110 感谢建议，这个问题已经有小伙伴反馈过了，现在已经改成了按下麦克风按钮开始录音，再次按下麦克风结束录音；同时也支持了快捷键，按住空格键录音，松掉空格键结束录音。#9

**Comment by scaactk** [comment]
hello, liou666,

Could you add the use of black space hotkey into the readme? That may be more convenient for users. I tried the new polyglot version and find that I need to click the microphone button every time after speaking. So I wonder who put forward this feature before, but luckily I find a solution in your response from a closed issue here. Other users may have similar confusion like me.

thanks,
Scaactk
