### ISSUE TITLE
[Help] Want new function of play the audio of my input

### ISSUE THREAD

**Issue by scaactk** [liou666/polyglot#29]
#### Describe the problem you confuse
Hi lion666,

Your program is excellent. I am using it to practice my pronunciation for a presentation. Duo to some UI display problems in the sourse-code based version on my computer, I am still using the release v0.1.1.

I am wandering if there will be a new feature that allow me to play my input in azure tts. Although the recognition of my voice is very accurate, as a user, my pronunciation and tone are not always excellent. It would be more helpful for English practice if I could hear how a text-to-speech (TTS) system speaks the content of my input.

thanks
scaactk

**Comment by liou666** [comment]
Hi, @scaactk 

Thank you for your feedback and suggestions. I have also considered this issue. It will be very helpful for speaking practice if I can play back my own voice. But on the other hand, saving voice takes up more storage space than saving text, so if you save voice, you may need to limit the number of conversations to save storage space🤔. So I am still looking for a better solution, and I need to continue to investigate before deciding whether to add this function.

btw, what is the UI problem encountered when the source code starts? 🤔

**Comment by AIFISHER** [comment]
赞助群友来梳理下有几个群友反馈的迫切需求，优先级从高到低，希望大佬有空了优化下哈：
一、希望加一个结束某一个语种语音输入的功能按钮，比如我们和英文AI对话完之后，有个按钮结束英文环境，然后切换到日语，就能识别我们说的日语。
二、希望加一个我们一次语音说完之后的结束词功能，说一个特定的词，像Siri唤醒功能一样，结束此次语音输入并自动发送。
三、希望加一个能回听我们说的语音的功能，这样能回查自己的口语哪里有问题。
四、支持多种格式的api key 不仅限于openai的key格式。支持其他语音模型（不只是微软的azure）。
五、token数量是否能再增加？
六、能否在单一语种对话环境内增加一个临时切换输入语言的功能？当有问题不知道如用外语表达想让gpt翻译的时候使用
七、是否能实现单独选词发音练习读音功能
八、是否能实现单独选择某句实现翻译功能？

**Comment by scaactk** [comment]
Hi, liou666, 

Sorry for the late response. I test the code-based version and the newly released version 0.2.0 on three different computers with win11. It showed the same UI problem as this [Link](https://imgloc.com/i/iMqfVN) It can't show the choices for languages and tones.'

best,
Scaactk

**Comment by scaactk** [comment]
I may solve the problem after I set the Azure speech service key, it works. I can select tone now. Thanks.

**Comment by liou666** [comment]
@scaactk Yes, the new version can only be used after entering your own azure key 🙂

**Comment by liou666** [comment]
audio support record
