### ISSUE TITLE
[Bug] 好像不支持换行符？

### ISSUE THREAD

**Issue by AndySze** [liou666/polyglot#33]
发现所有的回复，不管多长的文字都是一个段落，没有换行，是显示没有支持换行符吗？

**Comment by liou666** [comment]
hi, @AndySze   感谢反馈

目前没有对输出格式做处理，如果AI回复了一段markdown格式的代码，那么输出的格式看起来就不那么友好了。

但是我本意就是做一个语言交流的软件，其实也不应该让他回复代码片段，回复的文本也不会出现很长段落的情况。所以之后会考虑限制他的回复内容，而不是对输出格式做处理。🤔
