### ISSUE TITLE
Azure key如何申请

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [liou666/polyglot#34]
很棒的产品！请问Azure key如何申请？Azure区域应该怎么选？

**Comment by liou666** [comment]
@KAWAKO-in-GAYHUB
0.2.0版本使用语音服务需要配置自己的azure的 key，因为如果都用我的服务我也遭不住的。应用中内置一个语音服务的key，这个内置的服务需要输入访问密码后才能使用。一是为了防止我的语音服务被滥用，二是鼓励大家优先使用自己的语音服务。

要申请 Azure 语音服务的 API 密钥，可以按照以下步骤进行：（azure新用户有200刀的一个月免费额度）

+ 登录 Azure 门户 （[https://portal.azure.com/）](https://portal.azure.com/)
转到“Azure 语音服务”页面并单击“添加”按钮
+ 在“创建 Azure 语音服务”窗口中，选择订阅、资源组、区域，并为新服务指定名称
选择“F0”价格层，并单击“创建”
+ 创建完成后，转到新服务的“概述”页面，即可查看密钥和终结点

**Comment by Moo7818** [comment]
配置后提示1006未定义错误是什么情况？

**Comment by gavincoder-china** [comment]
语音合成失败,请检查语音配置：Unable to contact server. StatusCode: 1006, undefined Reason:  undefined,

**Comment by gavincoder-china** [comment]
> 语音合成失败,请检查语音配置：Unable to contact server. StatusCode: 1006, undefined Reason: undefined,

https://learn.microsoft.com/en-us/answers/questions/689962/speech-service-return-error-1006
这是微软关于该问题的回答 @liou666
