### ISSUE TITLE
[Bug] Unable to contact server

### ISSUE THREAD

**Issue by wyc888168** [liou666/polyglot#35]
#### Describe the bug
![image](https://user-images.githubusercontent.com/30308585/235035438-6a5a30b7-aac4-48e1-aeed-e0312207eabe.png)

When I tried to play the AI statement, it pops up the error, may I know how to fix it?

**Comment by liou666** [comment]
hi @wyc888168 
You need to check whether the following Azure Key has been configured in the setting page🤔

**Comment by zzworker** [comment]
![image](https://user-images.githubusercontent.com/4323686/235430326-e5ff80c1-6073-4c75-8aec-7a1fffec425a.png)
![image](https://user-images.githubusercontent.com/4323686/235432002-4a5486f7-9d5c-403c-9d84-8e0210e26c65.png)

语音合成失败,请检查语音配置：Unable to contact server. StatusCode: 1006, undefined Reason:  undefined, 
怎么看log，可以看出是什么问题？

**Comment by liou666** [comment]
@zhuangsheng 密钥需填写在Azure Access Key中，

**Comment by liou666** [comment]
close the issue
