### ISSUE TITLE
[Help] 帮忙看看是否能实现的需求

### ISSUE THREAD

**Issue by sellength** [liou666/polyglot#36]
#### Describe the problem you confuse
1、支持多种格式的api key 不仅限于openai的key格式。
2、token数量是否能再增加？
3、能否在单一语种对话环境内增加一个临时切换输入语言的功能？当有问题不知道如用外语表达想让gpt翻译的时候使用
4、是否能实现单独选词发音练习读音功能
5、是否能实现单独选择某句实现翻译功能？
6、希望加一个结束某一个语种语音输入的功能按钮，比如我们和英文AI对话完之后，有个按钮结束英文环境，然后切换到日语，就能识别我们说的日语。
7、希望加一个我们一次语音说完之后的结束词功能，说一个特定的词，像Siri唤醒功能一样，结束此次语音输入并自动发送。
8、希望加一个能回听我们说的语音的功能，这样能回查自己的口语哪里有问题。

**Comment by liou666** [comment]
需求整理
一、希望加一个结束某一个语种语音输入的功能按钮，比如我们和英文AI对话完之后，有个按钮结束英文环境，然后切换到日语，就能识别我们说的日语。
二、希望加一个我们一次语音说完之后的结束词功能，说一个特定的词，像Siri唤醒功能一样，结束此次语音输入并自动发送。
三、希望加一个能回听我们说的语音的功能，这样能回查自己的口语哪里有问题。
四、支持多种格式的api key 不仅限于openai的key格式。支持其他语音模型（不只是微软的azure）。
五、token数量是否能再增加？
六、能否在单一语种对话环境内增加一个临时切换输入语言的功能？当有问题不知道如用外语表达想让gpt翻译的时候使用
七、是否能实现单独选词发音练习读音功能
八、是否能实现单独选择某句实现翻译功能？

**Comment by ylacmilan** [comment]
回放自己说的话这个需求还是挺需要的
