### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by dongmuhds** [liou666/polyglot#37]
#### Describe the bug
尊敬的开发者你好：
我遇到了几个问题，向您反馈一下。
1.我设置日语时，语音发送时，无法修正内容，会将我的日语识别成英语。
2.chat在回复日语时，对话框中会将日语内容识别为英语。
3.日语输入的时候，会将输入法选择单词时的回车键识别为发送。

测试环境：macos Ventura 13.3
测试版本：Polyglot_0.2.0.dmg

**Comment by liou666** [comment]
hi @dongmuhds ，感谢反馈
对于问题1、2，我尝试过后不能复现出来，可以提供一个更加详细的复现步骤吗🤔？你也可以先试着切换角色后，再重新选择该日语角色进行对话，或者重启软件后，再次尝试，如果尝试后上述问题仍存在，我将继续排查该问题。
对于问题3，输入法选择bug，已修复。

**Comment by dongmuhds** [comment]
开发者您好,我将电脑重启后,1,2未复现,感谢您的修复.

**Comment by liou666** [comment]
暂时关闭issue，待1，2问题复现时提供具体的复现步骤后再打开，问题3已修复
