### ISSUE TITLE
[Help] 建议按住空格输入语音的时候，当前正在播放的语音可以停止

### ISSUE THREAD

**Issue by liangyimingcom** [liou666/polyglot#38]
[Help] 建议按住空格输入语音的时候，当前正在播放的音频可以停止

正在播放的音频建议增加一个停机键。因为对话几轮之后，gpt很容易就话唠句子很长，这时候等待音频结束时间太长了。
现在没办法只能关闭“自动播放音频“功能。

如上建议，希望采纳

**Comment by liou666** [comment]
@liangyimingcom 很好的建议，后续会考虑支持

**Comment by liangyimingcom** [comment]
**feaure of "tap voice in play to end playback" is work fine now, thanks for code update.** @liou666 #41
