### ISSUE TITLE
[Help] 请求语音合成失败的解决办法 1006

### ISSUE THREAD

**Issue by Moo7818** [liou666/polyglot#39]
程序弹出“语音合成失败,请检查语音配置：Unable to contact server. StatusCode: 1006, undefined Reason:  undefined, ”

**Comment by liou666** [comment]
@Moo7818 请检查是否正确配置了Azure Access Key和azure regionAzure 区域。

**Comment by Moo7818** [comment]
key和region都设置了，还有一个状况是new chat中无法选择语言及音色 无法下拉选框 也无法点击submit

**Comment by liou666** [comment]
看错误提示是你的key或者region配置出错了，new chat无法选择语言及音色 无法下拉选框就是因为你的语音服务不能用导致的。请检查一下你的key是否可用

**Comment by Moo7818** [comment]
已经解决了，问题出在我Endpoint输入到了key里，将key输入到了访问密码中。谢谢
