### ISSUE TITLE
[Bug] （未配置语音时）收到ai回复提醒“语音合成失败”后，光标会被冻结一段时间

### ISSUE THREAD

**Issue by ariaxo** [liou666/polyglot#43]
#### 如标题，此时在所有聊天页面中输入法都会被冻结无法输入任何内容。目测过个十几秒会恢复。但是很影响谈话体验...
![822XZ`_GA5JD3GP0I9OI5B3](https://github.com/liou666/polyglot/assets/97863000/e00aca81-ecdc-485c-b294-c8e21722a555)
![H~C@GWP _$ C4@EUD7V2D75](https://github.com/liou666/polyglot/assets/97863000/ebd3cd47-5bcc-4af1-a262-dfe556728656)

**Comment by liou666** [comment]
@ariaxo hi，bro. 

我尝试复现，但是没有成功。请提供一下你的操作系统版本，以及具体复现步骤

**Comment by ariaxo** [comment]
> @ariaxo hi，bro.
> 
> 我尝试复现，但是没有成功。请提供一下你的操作系统版本，以及具体复现步骤

@liou666 
`操作系统：windows 10`
![@_Z3( T%QT2NOAC8BK9S%EJ](https://github.com/liou666/polyglot/assets/97863000/13a87d36-a070-417b-8dd8-4d084015a0a1)
首先发送消息，由于我没有enable语音功能，会出现以下报错
![@M9EJ`MCUX$%XGDQR4JT(X](https://github.com/liou666/polyglot/assets/97863000/866f38b3-316c-46bc-a550-c2768d4637d8)
接着光标就会被冻结
---
但是不想用azure...

**Comment by ariaxo** [comment]
关闭自动合成语音可以解决
