### ISSUE TITLE
[Help] how to read your code, and contribute? 

### ISSUE THREAD

**Issue by renqibing** [liou666/polyglot#45]
How to read your code to understand the logical flow of the front-back end?
Can you show us an easy way to contribute to your code? 

I'm a language learner, targeting at improving TOEFL speaking. 
I'd like to implement an evaluation of AI for my answer, to improve my speaking. For example, after I respond to AI's question, AI could give me two replies, the first is the next question, and the second is the evaluation of my speaking. 

How can I modify your code in an easy way to achieve my goal? Thanks a lot!

**Comment by liou666** [comment]
Hi, @renqibing  great to hear you're contributing code to this app.

The basic process of contributing code is that you need to fork the code to your own github repository first, then modify the code, and finally submit the pr after the self-test is completed.

But before contributing code, you need to clarify the logic of the code and start it with the source code, which will help you understand the project clearly.

Then, for what you said you want to add a grammar scoring function, I suggest that you can refer to the implementation of the [translation function](https://github.com/liou666/polyglot/blob/main/src/pages/Home/components/Content.vue#L217). The scoring function is triggered by a "scoring" button. After clicking the button, the user's words will be sent to GPT. After getting a reply from GPT, it will be displayed in interface.

Hope the above is helpful to you and look forward to your contribution😊

**Comment by renqibing** [comment]
Thank you for your quick response! To achieve my goal of grammar scoring, I need to understand the data flow of one communication between the user and ai. For example, can you tell me where we receive the user's question and send the question to ai, then receive the ai's response? I need to send the user's question with my defined prompt to ai again, to obtain another response from ai. How do I modify your code as littile as possible to achieve my goal?

**Comment by liou666** [comment]
hi @renqibing 
I think you can refer to the [translate function](https://github.com/liou666/polyglot/blob/main/src/pages/Home/components/Content.vue#L217) 🤔
