### ISSUE TITLE
[Help] mac 客户端无法打开

### ISSUE THREAD

**Issue by dwqs** [liou666/polyglot#48]
#### mac 客户端无法打开
<img width="248" alt="image" src="https://github.com/liou666/polyglot/assets/7871813/a79035a0-2aa0-4b68-887c-83447ecbb4d4">

mac 信息：

<img width="194" alt="image" src="https://github.com/liou666/polyglot/assets/7871813/54502b32-d362-4d65-b526-452e6dcdb335">

**Comment by liou666** [comment]
@dwqs 请查看 [常见问题](https://github.com/liou666/polyglot#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by dwqs** [comment]
您的邮件已经收到，我会尽快回复，谢谢！
