### ISSUE TITLE
[Bug] internet request timeout

### ISSUE THREAD

**Issue by LostBirdx** [liou666/polyglot#5]
#### Describe the bug
![image](https://user-images.githubusercontent.com/23292303/231908217-fba2520b-e74a-4abd-b2b8-b07c712fcd95.png)

I already used global proxy and it doesn't work.

**Comment by liou666** [comment]
This should be caused by the slow response of openapi, I limited the timeout to 10 seconds, and if the api responds in time, it will prompt a timeout. You can try to change the network node, or use a proxy.

**Comment by LostBirdx** [comment]
Thanks for your reply. It actually because i haven't add the openai api and azure api ...     I'm a newbee of ts.

**Comment by LostBirdx** [comment]
by the way, it's such a good product, I really appreciate your work!
