### ISSUE TITLE
[建议] 可以设置语速调节吗？可以列出微软语音的发音列表，让用户自选喜欢的语音吗？

### ISSUE THREAD

**Issue by hub3918** [liou666/polyglot#50]
可以設置語速調節嗎

**Comment by liou666** [comment]
hi @realchris007 
目前再新建角色的时候可以设置语速，并可以自由喜欢的语音。gpt回复的消息目前也是支持重听的。

回复内容可模糊显示目前还没做，下个版本会考虑加上

**Comment by liou666** [comment]
内容模糊功能已在0.3.1版本加上
