### ISSUE TITLE
求linux版本~~~~~~~~

### ISSUE THREAD

**Issue by acodervic** [liou666/polyglot#51]
求linux版本~~~~~~~~

**Comment by liou666** [comment]
hi，@acodervic 
计划下个版本会打包linux版本。

但是我没有linux系统，所以不能在linux做测试，之后发布的时候可能会一些bug存在😅

**Comment by acodervic** [comment]
> hi，@acodervic 计划下个版本会打包linux版本。
> 
> 但是我没有linux系统，所以不能在linux做测试，之后发布的时候可能会一些bug存在sweat_smile

好的,没问题

**Comment by liou666** [comment]
linux版本已支持
