### ISSUE TITLE
[Bug] 语音识别不能正常使用

### ISSUE THREAD

**Issue by jienigui20010601** [liou666/polyglot#6]
#### Describe the problem you confuse
为什么我打开之后代理有问题，然后我输入语言一直录入不上。

**Comment by liou666** [comment]
你是下载的安装包还是直接源码启动的？源码启动的话需要在.env文件中配置环境变量

**Comment by jienigui20010601** [comment]
我下载的安装包，装上之后，也是录音功能有问题，但是文字交流没问题

**Comment by liou666** [comment]
请提供一下电脑的系统版本

**Comment by liou666** [comment]
@jienigui20010601 0.2.0版本已解决，更新最新版本即可 https://github.com/liou666/polyglot/releases
