### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by zapp926** [liou666/polyglot#60]
<img width="1673" alt="polyglot-1" src="https://github.com/liou666/polyglot/assets/35788274/b51886a1-f407-43d5-9bb3-b78d716e3d83">
<img width="1680" alt="polyglot-2" src="https://github.com/liou666/polyglot/assets/35788274/9ae09225-74b4-42a7-9933-a90796ea1274">
请问我已经配置了GPT和Azure的Key，为什么出现图片中的错误。没有生成语音回答呢？

我用的是Mac版，也试了Web版，都是同样的错误。谢谢。

**Comment by liou666** [comment]
@zapp926 网络请求超时了，可以试下科学上网，或者换个节点尝试一下

**Comment by zapp926** [comment]
@liou666 好的 谢谢
