### ISSUE TITLE
[建议] 希望能自定义语法检查功能的prompt

### ISSUE THREAD

**Issue by Heithon** [liou666/polyglot#61]
![image](https://github.com/liou666/polyglot/assets/85172139/2ef99ce4-2064-4bed-a009-9632aab47886)
小灯泡点击之后，似乎只能进行语法检查

建议：
1. 希望能自定义这个prompt，比如有时候想让ai给出几个更加地道的改进版本，或者是让ai换种表达风格之类的。
2. 希望能给ai的聊天框也加上这个功能，同样是自定义prompt，这样就可以一键总结ai句子里的知识点，或者进行语法分析，生词积累等。

创建bot时能自定义这些，应该可以让学习更加灵活，学习方式更丰富👍🏻

**Comment by liou666** [comment]
hi , @Heithon 感谢使用该软件，并提出改进建议。

你的这个想法很棒，这也是我刚开始做语法检查时候的想法。之所以一直没做的原因是：

根据大家的反馈来看， prompt自定义虽然可以给用户带来很大的灵活性。但是对于相当一部分“小白“用户来说增加一个自定义配置，就会相应增加软件的使用复杂度。更多人还是希望能够降低软件的使用复杂度、最好是打开之后不需要任何配置就可以直接用。 

所以这一块还需要在权衡之后在考虑加入，目前计划是在之后的版本做到两者兼顾， 也就是在prompt可以自定义的同时，也内置一些比较常用prompt。


补充：
如果大家有一些好用的prompt也可以提供出来，我内置到软件里面去。😊
