### ISSUE TITLE
[Bug] Mac版本，回复的语音会自己填到输入框中

### ISSUE THREAD

**Issue by Fick707** [liou666/polyglot#63]
#### Mac版本 0.3.4,回复的语音会自己填到输入框中,如下图所示

<img width="858" alt="bug001" src="https://github.com/liou666/polyglot/assets/6091016/c72616da-be6e-4056-aec3-d269665f4b56">

另外，我用语音发起请求时，发出来的内容竟然是两遍，如下图：

<img width="695" alt="image" src="https://github.com/liou666/polyglot/assets/6091016/923d2cfe-ccfc-474e-bcfb-7b729653e895">

**Comment by Fick707** [comment]
我发现，它不仅在将响应内容填进去，而是将所有听到的声音转进去了。
就是没点录音的情况下，它在识别我电脑听到的声音。

**Comment by Fick707** [comment]
重启一下好了，可能是我第一次使用时，用尝试使用空格键时不知道怎么操作，就乱按了一通导致的。重启之后没有复现

**Comment by liou666** [comment]
hi @Fick707 
由于我一直没有复现出来，不好排查， 如果之后有具体的复现过程，可以提供一下，我再排查
