### ISSUE TITLE
@wuliangtdi 之后Web端会考虑使用vercel部署，桌面端的话还是需要手动打包

### ISSUE THREAD

**Issue by laike** [liou666/polyglot#66]
@wuliangtdi 之后Web端会考虑使用vercel部署，桌面端的话还是需要手动打包

_Originally posted by @liou666 in https://github.com/liou666/polyglot/issues/56#issuecomment-1602817915_
            
请问什么时候启用web端啊 不知道怎么启动web版本

**Comment by liou666** [comment]
hi @laike 
项目是用electron打包的，本质上还是属于web代码，你可以把src中的文件提出来单独打包部署就是web版本
