### ISSUE TITLE
[Help] 请提供适配M系列芯片的Mac平台客户端

### ISSUE THREAD

**Issue by LonePheasantWarrior** [liou666/polyglot#67]
polyglot是我苹果电脑中唯一一款Intel类型的APP,让人感到沮丧,希望早日推出原生ARM的Mac客户端!
截止到当前最新的客户端版本是[v0.3.5](https://github.com/liou666/polyglot/releases/tag/v0.3.5)

<img width="1171" alt="image" src="https://github.com/liou666/polyglot/assets/37655011/b28af55d-e3b6-4042-8c0a-e193575e2b0d">

**Comment by liou666** [comment]
hi, @LonePheasantWarrior 

感谢建议，我会尽快提供x64(Inter)与arm64(Apple Silicon)的双版本支持。

**Comment by liangyimingcom** [comment]
arm洁癖😊

**Comment by XiaopengZzh** [comment]
非常感谢大佬的贡献，另外希望能照顾一下我们这些洁癖患者😂，早日更新arm版本

**Comment by liou666** [comment]
@LonePheasantWarrior  0.3.6版本已支持arm64(Apple Silicon)
