### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by q1121253041** [liou666/polyglot#68]
#### Describe the problem you confuse
Hello，大佬，我在pc 上使用app中接入了chatgpt3.5 的api，但是报错，我想问下问题出在哪了？
Unexpected  token < in JSON at positon 0

**Comment by liou666** [comment]
hi @q1121253041, 看报错像是网络请求超时了，使用自己的api需要科学上网。

**Comment by q1121253041** [comment]
hello 大佬  已经科学上网过了

**Comment by q1121253041** [comment]
谢谢回复，找到问题了，由于api代理默认不为空，导致，将值删掉就好了

**Comment by liou666** [comment]
ok🙂
