### ISSUE TITLE
[Help] 为什么录音录不上？

### ISSUE THREAD

**Issue by flistz** [liou666/polyglot#7]
#### Describe the problem you confuse
下了mac版，设置了api key，文字沟通可以，录音功能一直卡住，然后报错，请问使用录音功能需要设置代理吗？
<img width="800" alt="image" src="https://user-images.githubusercontent.com/66770519/232264354-fa74daac-48b4-480d-913d-4b82428a27f1.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/66770519/232264385-c4de9522-c487-4762-be42-0050def0fba3.png">

**Comment by liou666** [comment]
录音功能不需要设置代理
录音功能卡住，可能是应用没有麦克风权限，检查一下是否开启了麦克风权限。

**Comment by jienigui20010601** [comment]
我也是一样的，录音有问题，求解

**Comment by jienigui20010601** [comment]
![image](https://user-images.githubusercontent.com/130365456/232301997-21b69c81-b7fb-4b51-bbab-240dc13d85cd.png)

**Comment by jienigui20010601** [comment]
权限没问题，但是录音没用

**Comment by pampam8023** [comment]
macOS也有同样的问题

**Comment by pampam8023** [comment]
我在macOS上也遇到同样的问题。

**Comment by liou666** [comment]
你好，请提供一下你们的系统版本

**Comment by liou666** [comment]
我认为可能是网络原因，没有加载到语言包。
请提供一下你们的系统版本，并检查一下新建角色时是否可以选择语言和音色。

**Comment by pampam8023** [comment]
MacBook Pro 13.2.1 (22D68)  录音权限已开 / 可以新建角色/可以输入文字获得回应, 但点击录音时无法正常运行
<img width="785" alt="image" src="https://user-images.githubusercontent.com/25924903/232333142-0fba79f1-f01c-4117-adc9-5cf82b95d6ef.png">

**Comment by liou666** [comment]
感谢你提供的信息，我将会尽快复现排查一下。

**Comment by xufengnian** [comment]
MacOS遇到同样的问题

**Comment by liou666** [comment]
@xufengnian @pampam8023 @jienigui20010601 @flistz 0.2.0版本已解决，更新最新版本即可 https://github.com/liou666/polyglot/releases
