### ISSUE TITLE
[Bug] A bug occurs in multiple rounds of dialogue

### ISSUE THREAD

**Issue by flistz** [liou666/polyglot#70]
#### Describe the bug
<img width="763" alt="image" src="https://github.com/liou666/polyglot/assets/66770519/6fc94f2b-f82b-4789-8f22-65c88ce52bd2">

This error occurs when I am 2 or 3 rounds into the conversation. Then occasionally there will be an inability to connect to the service.

**Comment by liou666** [comment]
hi,@flistz I'm sorry for the late reply. 

I guess this is caused by the delay network🤔, it has been optimized in version 0.3.6, you can try to download the latest version of polyglot to solve it If updating to the latest version still doesn't work, please let me know.
