### ISSUE TITLE
[Bug] AppImage文件无法运行

### ISSUE THREAD

**Issue by zxp19821005** [liou666/polyglot#72]
如题。
https://github.com/liou666/polyglot/releases/tag/v0.3.6
https://github.com/liou666/polyglot/releases/download/v0.3.6/Polyglot_0.3.6.AppImage
下载好多遍，换过多个proxy，给予权限后无法正常运行，提示文件错误。

**Comment by liou666** [comment]
hi @zxp19821005 你好，请提供一下电脑系统版本。以及报错截图

**Comment by zxp19821005** [comment]
- OS: EndeavourOS
- Kernel: 6.1.68-1-lts
我已经将软件移植到了ArchLinux的AUR：https://aur.archlinux.org/packages/polyglot-ai-bin
![image](https://github.com/liou666/polyglot/assets/4915850/1a054819-44ef-4de2-94b2-7b00a6784411)
