### ISSUE TITLE
[Bug] Unexpected end of JSON input

### ISSUE THREAD

**Issue by heiheiheibj** [liou666/polyglot#73]
输入什么内容，都提示出错
梯子没问题，可以使用OPENAI服务
谢谢
#### Describe the bug
![image](https://github.com/liou666/polyglot/assets/6910198/492f03db-2cdd-4998-8a6d-48229e5f5a77)

![image](https://github.com/liou666/polyglot/assets/6910198/5f3e3911-86a4-4cdb-a369-ee4cf0631995)

**Comment by liou666** [comment]
@heiheiheibj 我推测是你配置的API代理有问题，请检查设置界面你配置的API代理是否可以正常使用？或者不设置API代理后再次尝试

**Comment by heiheiheibj** [comment]
不设代理就连不上，提示 Failed to fetch 。梯子肯定是没问题，上openai官网和用其它软件，都是正常滴。切了不同国家的IP，都还是一样。软件有没有什么日志模式能看到哪出错不。谢谢
![image](https://github.com/liou666/polyglot/assets/6910198/60731faa-9eef-4749-a3ec-3d44ba54280c)

**Comment by liou666** [comment]
@heiheiheibj 我的意思是，你配置的http://127.0.0.1:7890 API代理可能是有问题的，你把这里的代理去掉尝试一下呢
<img width="532" alt="image" src="https://github.com/liou666/polyglot/assets/70936517/483fef04-7786-4412-b1f8-2426e5ccdd9a">

**Comment by heiheiheibj** [comment]
谢谢，是我的设的问题，把梯子打开全局模式就好使了。不过去Azure注语音服务，又是各种妖蛾子，唉，算了

**Comment by liou666** [comment]
@heiheiheibj Readme中有如何注册语音服务的教程，你可以参考一下

**Comment by heiheiheibj** [comment]
好的。感谢。
