### ISSUE TITLE
翻译功能无法使用

### ISSUE THREAD

**Issue by billowssun** [liou666/polyglot#77]
翻译功能无法正常使用，正常使用语音服务，AzureAPI填写正确。

**Comment by liou666** [comment]
@billowssun 请提供一下你的设置界面还有翻译报错的截图。

**Comment by billowssun** [comment]
![image](https://github.com/liou666/polyglot/assets/55521033/9c918ca7-efe3-4776-8ab8-7f65974a44a0)
![image](https://github.com/liou666/polyglot/assets/55521033/2cc1d939-09e3-4f31-af8b-d9f01d6761cc)
![image](https://github.com/liou666/polyglot/assets/55521033/eed2d5a3-99e2-46f9-98ae-009b9b18ad5c)

**Comment by billowssun** [comment]
问题是openai api key不稳定导致的。
