### ISSUE TITLE
[Help] 可以新增国内的一些api key吗？

### ISSUE THREAD

**Issue by Rancho-7** [liou666/polyglot#78]

**Comment by liou666** [comment]
@Rancho-7 国内API key是指语音服务的API Key还是聊天服务的API Key？ 以我目前所了解到的国内的一些API key效果都不是特别好

**Comment by Rancho-7** [comment]
聊天服务的api key，弄成可选的这种？国内的api可以使用azure的语音吗？

**Comment by liou666** [comment]
@Rancho-7
 1.  国内的聊天服务API key是指哪一家的API key？你有推荐的一些吗？因为我了解到的国内AI厂商能力相较于国外的AI厂商能力还是比较偏弱的。
 2. azure的语音国内国外都可以用。
