### ISSUE TITLE
[Help] 当前分组 default 下对于模型 gpt-3.5-turbo-0301 无可用渠道 的问题。

### ISSUE THREAD

**Issue by Rancho-7** [liou666/polyglot#79]
我使用的gpt-3.5-turbo，请问部分功能不支持这个模型吗？
<img width="996" alt="image" src="https://github.com/user-attachments/assets/e2da99ad-40b6-4e27-aea2-41b360c53255">

**Comment by liou666** [comment]
@Rancho-7  目前软件内对gpt-3.5-turbo系列模型 仅支持gpt-35-turbo-16k gpt-35-turbo-instruct
