### ISSUE TITLE
[功能需求] 连续对话

### ISSUE THREAD

**Issue by wuliangtdi** [liou666/polyglot#8]
#### Describe the problem you confuse
就是我想问一下能否实现连续对话功能呢?能实现的话那确实就感觉像是在对话

**Comment by liou666** [comment]
你好，目前对话是关联上下文的，可以具体的描述一下你所说的连续对话功能吗？

**Comment by wuliangtdi** [comment]
就是你问一句，它答一句。再问一句，它再答一句。中途不需要按那个麦克风按钮(就跟siri和小爱同学那种的连续对话)

**Comment by liou666** [comment]
我明白了，之后会新增一种对话模式，也就是这种连续对话的模式，可以自己选择是否开启。 
非常好的想法，感谢你的建议。💖

**Comment by wuliangtdi** [comment]
期待😍😍

**Comment by liou666** [comment]
我最近尝试实现连续对话功能，但是遇到了一些阻碍问题。就是在连续对话时，由于azure sdk的限制，我无法准确的判断何时语音结束🤔。我尝试调研了一些解决方案，但是也没有取得很好的进展。

如果大家有好的实现方案，欢迎交流与提PR

**Comment by xgd561** [comment]
> 我最近尝试实现连续对话功能，但是遇到了一些阻碍问题。就是在连续对话时，由于azure sdk的限制，我无法准确的判断何时语音结束🤔。我尝试调研了一些解决方案，但是也没有取得很好的进展。
> 
> 如果大家有好的实现方案，欢迎交流与提PR

可以考虑让用户自己定义结束输入的关键词over，用户觉得自己说完了，可以再后面加一个over，你根据这个over来判断语音输入结束
