### ISSUE TITLE
希望允许用户编辑翻译prompt和语法prompt

### ISSUE THREAD

**Issue by yingzwang** [liou666/polyglot#80]
在编辑角色里，希望可以加入翻译prompt和语法prompt，允许用户修改预设的prompt.
场景：翻成其他语言（非中文），语法老师给出更详细的讲解和示例并使用其他语言（非中文）

**Comment by liou666** [comment]
@yingzwang hi，
+ 自定义prompt是个很好的想法，但是自定义prompt会带来更大灵活度的同时，也会给用户增加使用上的复杂度。
+ 我目前对于这款软件的定位是开箱即用，软件尽可能的轻量化，所以目前还没有增加更多自定义prompt的打算。

**Comment by liou666** [comment]
如果有需要的话，或许可以参考一下“新建角色中自定义场景预设”的实现逻辑自行实现。
