### ISSUE TITLE
[Help] SPACE - Keyboard shortcuts

### ISSUE THREAD

**Issue by 0xueping** [liou666/polyglot#9]
#### Describe the feature I hope
I hope the SPACE button keyboard shortcuts.
Press-and-hold SPACE (outside text input) to record, and release to submit.

**Comment by liou666** [comment]
Nice idea! I'd like to add this feature, If anyone wants to try it, welcome to mention pr.

**Comment by liou666** [comment]
@Pengree Nice idea! I'd like to add this feature, If anyone wants to try it, welcome to mention pr.
